steps:
  # Instala dependências do backend
  - name: 'node:18'
    dir: 'backend'
    args: ['npm', 'install']

  # Build do backend (se tiver build)
  - name: 'node:18'
    dir: 'backend'
    args: ['npm', 'run', 'build']  # Se tiver script "build"

  # Deploy do backend no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy revir-backend \
          --source backend/ \
          --region us-central1 \
          --allow-unauthenticated \
          --project poc-revir


  # Opcional: Frontend (descomente quando for implementar)
  # - name: 'node:18'
  #   dir: 'frontend'
  #   args: ['npm', 'install']
  # - name: 'node:18'
  #   dir: 'frontend'
  #   args: ['ng', 'build', '--prod']
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gsutil cp -r frontend/dist/frontend/* gs://<seu-bucket>/public/

# timeout: '1200s' # Tempo máximo de execução (ajuste conforme necessário)