name: Backend CI & Deploy (Express + Vercel)

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (backend)
        run: npm ci
        working-directory: ./backend

      - name: Lint / Test (skip if none)
        run: echo "No tests configured"

      - name: Install Vercel CLI
        run: npm install -g vercel --no-progress
        working-directory: ./backend

      - name: Deploy to Vercel (backend)
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./backend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}