name: Frontend CI & Deploy (Vite + Vercel)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build (Vite)
        run: npm run build
        working-directory: ./frontend

      - name: Install Vercel CLI
        run: npm install -g vercel@latest      

      - name: Deploy to Vercel (frontend)
        run: |
          npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./frontend

        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}